accessing
langOptions
	"^ #(az be bg cs de en es fr hy it lt mk pl pt ro ru tr uk)"
	^ OrderedCollection new
		add: {'Aleman' . #de};
		add: {'Armenio' . #hy};
		add: {'Azerbaiyano' . #az};
		add: {'Bielorruso' . #be};
		add: {'Bulgaro' . #bg};
		add: {'Checo' . #cs};
		add: {'Español' . #es};
		add: {'Frances' . #fr};
		add: {'Ingles' . #en};
		add: {'Italiano' . #it};
		add: {'Lituano' . #lt};
		add: {'Macedonio' . #mk};
		add: {'Polaco' . #pl};
		add: {'Portugues' . #pt};
		add: {'Rumano' . #ro};
		add: {'Ruso' . #ru};
		add: {'Turco' . #tr};
		add: {'Ucraniano' . #uk};
		yourself